export type PracticalInfo = {
  visa: string;
  plug: string;
  emergency: string;
  tipping: string;
  language: string;
  timezone: string;
};

const DEFAULT_INFO: PracticalInfo = {
  visa: "Exemption de visa jusqu’à 90 jours pour les citoyens UE / CH / CA — vérifiez selon votre nationalité.",
  plug: "Type C/E, 230V — prise universelle recommandée.",
  emergency: "112 (numéro d’urgence européen, valable dans la plupart des pays).",
  tipping: "Non obligatoire, apprécié si arrondi ou 5–10% au restaurant.",
  language: "Anglais courant dans les zones touristiques.",
  timezone: "Vérifiez le décalage avec votre ville de départ avant de caler vos appels.",
};

export const PRACTICAL_INFO: Record<string, PracticalInfo> = {
  France: {
    visa: "Aucun visa pour les citoyens UE / CH — passeport ou CNI valide.",
    plug: "Type C/E, 230V.",
    emergency: "112 (urgences générales), 15 (SAMU), 17 (police).",
    tipping: "Service compris par la loi, pourboire en plus rare mais apprécié.",
    language: "Français. \"Bonjour\", \"merci\", \"l’addition s’il vous plaît\".",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  "Royaume-Uni": {
    visa: "Exemption de visa jusqu’à 6 mois pour UE / CH / CA (passeport valide requis post-Brexit).",
    plug: "Type G, 230V — adaptateur obligatoire depuis l’UE.",
    emergency: "999 ou 112.",
    tipping: "10–12,5% au restaurant si non inclus, pas obligatoire ailleurs.",
    language: "Anglais.",
    timezone: "UTC+0 (UTC+1 en été).",
  },
  Allemagne: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10%, arrondir l’addition est la norme.",
    language: "Allemand. \"Hallo\", \"danke\", \"die Rechnung, bitte\".",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Espagne: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "Non obligatoire, petite monnaie appréciée.",
    language: "Espagnol. \"Hola\", \"gracias\", \"la cuenta, por favor\".",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Italie: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F/L, 230V.",
    emergency: "112.",
    tipping: "Service souvent compris (coperto), pourboire en plus rare.",
    language: "Italien. \"Ciao\", \"grazie\", \"il conto, per favore\".",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Portugal: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10% apprécié, rarement obligatoire.",
    language: "Portugais. \"Olá\", \"obrigado/a\", \"a conta, por favor\".",
    timezone: "UTC+0 (UTC+1 en été).",
  },
  Grèce: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10% apprécié au restaurant.",
    language: "Grec. \"Γεια σου (Yassou)\", \"ευχαριστώ (efharisto)\".",
    timezone: "UTC+2 (UTC+3 en été).",
  },
  "Pays-Bas": {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10%, souvent arrondi.",
    language: "Néerlandais, anglais très répandu.",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Autriche: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10%, arrondir l’addition.",
    language: "Allemand.",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Hongrie: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "10%, souvent attendu au restaurant.",
    language: "Hongrois, anglais répandu dans le tourisme.",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Tchéquie: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/E, 230V.",
    emergency: "112.",
    tipping: "10%, souvent arrondi ou ajouté.",
    language: "Tchèque, anglais répandu à Prague.",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Suède: {
    visa: "Aucun visa pour les citoyens UE / CH.",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "Non obligatoire, souvent inclus.",
    language: "Suédois, anglais quasi universel.",
    timezone: "UTC+1 (UTC+2 en été).",
  },
  Irlande: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type G, 230V.",
    emergency: "112 ou 999.",
    tipping: "10% au restaurant si service apprécié.",
    language: "Anglais (et irlandais).",
    timezone: "UTC+0 (UTC+1 en été).",
  },
  Turquie: {
    visa: "e-Visa en ligne obligatoire pour la plupart des nationalités (env. 50 USD, valable 90 jours).",
    plug: "Type C/F, 230V.",
    emergency: "112.",
    tipping: "5–10% au restaurant, apprécié pour les guides et chauffeurs.",
    language: "Turc. \"Merhaba\", \"teşekkürler\", \"hesap lütfen\".",
    timezone: "UTC+3 (pas de changement d’heure).",
  },
  Maroc: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type C/E, 220V.",
    emergency: "19 (police), 15 (urgences médicales).",
    tipping: "10–15%, très courant (guides, chauffeurs, restaurants).",
    language: "Arabe, français très répandu.",
    timezone: "UTC+1, pas de changement d’heure.",
  },
  Égypte: {
    visa: "e-Visa en ligne ou visa à l’arrivée (env. 25 USD) pour la plupart des nationalités.",
    plug: "Type C/F, 220V.",
    emergency: "122 (police), 123 (ambulance).",
    tipping: "Baksheesh attendu presque partout, prévoir petites coupures.",
    language: "Arabe, anglais répandu dans le tourisme.",
    timezone: "UTC+2, pas de changement d’heure.",
  },
  "Afrique du Sud": {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type M (spécifique), 230V — adaptateur dédié nécessaire.",
    emergency: "10111 (police), 10177 (ambulance), 112 (mobile).",
    tipping: "10–15% au restaurant, courant pour tout service.",
    language: "Anglais, afrikaans, zoulou et 8 autres langues officielles.",
    timezone: "UTC+2, pas de changement d’heure.",
  },
  Kenya: {
    visa: "e-Visa (eTA) obligatoire en ligne avant le départ (~30 USD).",
    plug: "Type G, 230V.",
    emergency: "999 ou 112.",
    tipping: "10% au restaurant, apprécié pour guides safari.",
    language: "Swahili, anglais.",
    timezone: "UTC+3, pas de changement d’heure.",
  },
  "Émirats arabes unis": {
    visa: "Visa à l’arrivée gratuit jusqu’à 30–90 jours selon nationalité (UE / CH / CA inclus).",
    plug: "Type G, 230V.",
    emergency: "999 (police), 998 (ambulance).",
    tipping: "10–15%, souvent déjà inclus en service charge.",
    language: "Arabe, anglais très répandu.",
    timezone: "UTC+4, pas de changement d’heure.",
  },
  Qatar: {
    visa: "Visa à l’arrivée gratuit jusqu’à 30 jours pour la plupart des nationalités.",
    plug: "Type G, 240V.",
    emergency: "999.",
    tipping: "10%, souvent déjà inclus.",
    language: "Arabe, anglais très répandu.",
    timezone: "UTC+3, pas de changement d’heure.",
  },
  Japon: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type A/B, 100V — adaptateur nécessaire (et parfois convertisseur).",
    emergency: "110 (police), 119 (pompiers/ambulance).",
    tipping: "Absent, voire perçu comme déplacé — ne pas laisser de pourboire.",
    language: "Japonais. \"Konnichiwa\", \"arigatō\", \"okaikei onegaishimasu\".",
    timezone: "UTC+9, pas de changement d’heure.",
  },
  "Corée du Sud": {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA (K-ETA en ligne requis).",
    plug: "Type C/F, 220V.",
    emergency: "112 (police), 119 (ambulance/pompiers).",
    tipping: "Absent, non attendu.",
    language: "Coréen, anglais limité hors zones touristiques.",
    timezone: "UTC+9, pas de changement d’heure.",
  },
  Chine: {
    visa: "Visa obligatoire à obtenir avant le départ (sauf transit courte durée dans certaines villes).",
    plug: "Type A/C/I, 220V.",
    emergency: "110 (police), 120 (ambulance).",
    tipping: "Absent, parfois mal perçu.",
    language: "Mandarin. VPN recommandé pour les apps occidentales.",
    timezone: "UTC+8, pas de changement d’heure.",
  },
  "Hong Kong": {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type G, 220V.",
    emergency: "999.",
    tipping: "10% souvent déjà inclus (service charge).",
    language: "Cantonais, anglais très répandu.",
    timezone: "UTC+8, pas de changement d’heure.",
  },
  Singapour: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type G, 230V.",
    emergency: "999 (police), 995 (ambulance).",
    tipping: "Non attendu, souvent inclus (service charge 10%).",
    language: "Anglais, mandarin, malais, tamoul.",
    timezone: "UTC+8, pas de changement d’heure.",
  },
  Malaisie: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type G, 230V.",
    emergency: "999.",
    tipping: "Non obligatoire, souvent inclus.",
    language: "Malais, anglais très répandu.",
    timezone: "UTC+8, pas de changement d’heure.",
  },
  Thaïlande: {
    visa: "Exemption de visa jusqu’à 30–60 jours selon nationalité (UE / CH / CA inclus).",
    plug: "Type A/C/O, 220V.",
    emergency: "191 (police), 1669 (ambulance).",
    tipping: "Non obligatoire, petite monnaie appréciée.",
    language: "Thaï. \"Sawadee ka/krub\", \"khob khun ka/krub\".",
    timezone: "UTC+7, pas de changement d’heure.",
  },
  "Indonésie (Bali)": {
    visa: "Visa à l’arrivée payant (~35 USD), valable 30 jours, prolongeable une fois.",
    plug: "Type C/F, 230V.",
    emergency: "112 (général), 118 (ambulance).",
    tipping: "Non obligatoire, apprécié (10 000–20 000 IDR).",
    language: "Indonésien/balinais, anglais répandu dans le tourisme.",
    timezone: "UTC+8, pas de changement d’heure.",
  },
  Inde: {
    visa: "e-Visa obligatoire à demander en ligne avant le départ.",
    plug: "Type C/D/M, 230V.",
    emergency: "112 (général), 102 (ambulance).",
    tipping: "5–10%, apprécié presque partout.",
    language: "Hindi, anglais très répandu.",
    timezone: "UTC+5:30, pas de changement d’heure.",
  },
  "États-Unis": {
    visa: "ESTA obligatoire en ligne avant le départ pour UE / CH (Visa Waiver Program).",
    plug: "Type A/B, 120V — adaptateur et parfois convertisseur nécessaires.",
    emergency: "911.",
    tipping: "15–20% au restaurant, quasi obligatoire (salaires bas dans le service).",
    language: "Anglais.",
    timezone: "Variable selon l’État (UTC-5 à UTC-8).",
  },
  Canada: {
    visa: "AVE (autorisation de voyage électronique) obligatoire en ligne pour UE / CH.",
    plug: "Type A/B, 120V.",
    emergency: "911.",
    tipping: "15–20% au restaurant, attendu.",
    language: "Anglais, français au Québec.",
    timezone: "Variable selon la province (UTC-3:30 à UTC-8).",
  },
  Mexique: {
    visa: "Exemption de visa jusqu’à 180 jours pour UE / CH / CA.",
    plug: "Type A/B, 127V.",
    emergency: "911.",
    tipping: "10–15% au restaurant, attendu.",
    language: "Espagnol. \"Hola\", \"gracias\", \"la cuenta, por favor\".",
    timezone: "Variable selon la région (UTC-5 à UTC-8).",
  },
  Argentine: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH / CA.",
    plug: "Type C/I, 220V.",
    emergency: "911.",
    tipping: "10% au restaurant, courant.",
    language: "Espagnol.",
    timezone: "UTC-3, pas de changement d’heure.",
  },
  Brésil: {
    visa: "Exemption de visa jusqu’à 90 jours pour UE / CH (vérifier pour le Canada).",
    plug: "Type C/N, 127V/220V selon région.",
    emergency: "190 (police), 192 (ambulance).",
    tipping: "10%, souvent déjà inclus au restaurant.",
    language: "Portugais.",
    timezone: "UTC-3, pas de changement d’heure.",
  },
  Australie: {
    visa: "eVisitor ou ETA obligatoire en ligne avant le départ pour UE / CH / CA.",
    plug: "Type I, 230V.",
    emergency: "000.",
    tipping: "Non obligatoire, salaires du service déjà corrects.",
    language: "Anglais.",
    timezone: "Variable selon l’État (UTC+8 à UTC+10:30).",
  },
};

export function getPracticalInfo(country: string): PracticalInfo {
  return PRACTICAL_INFO[country] ?? DEFAULT_INFO;
}
