export const TRANSIT_LINKS: Record<string, { label: string; url: string }> = {
  "Bogotá": { label: "TransMilenio", url: "https://www.transmilenio.gov.co" },
  Osaka: { label: "Osaka Metro", url: "https://www.osakametro.co.jp/en/" },
  Paris: { label: "Île-de-France Mobilités", url: "https://www.iledefrance-mobilites.fr/le-reseau/plans" },
  Tokyo: { label: "Tokyo Metro", url: "https://www.tokyometro.jp/en/subwaymap/index.html" },
  Kyoto: { label: "Kyoto City Subway & Bus", url: "https://www.city.kyoto.lg.jp/kotsu/" },
  London: { label: "Transport for London", url: "https://tfl.gov.uk/maps/track/tube" },
  "New York": { label: "MTA", url: "https://new.mta.info/maps" },
  Rome: { label: "ATAC", url: "https://www.atac.roma.it" },
  Barcelona: { label: "TMB", url: "https://www.tmb.cat" },
  Berlin: { label: "BVG", url: "https://www.bvg.de" },
  Munich: { label: "MVV", url: "https://www.mvv-muenchen.de" },
  Singapore: { label: "LTA / SMRT", url: "https://www.lta.gov.sg" },
  "Hong Kong": { label: "MTR", url: "https://www.mtr.com.hk" },
  Seoul: { label: "Seoul Metro", url: "https://www.seoulmetro.co.kr" },
  Amsterdam: { label: "GVB", url: "https://www.gvb.nl" },
  Vienna: { label: "Wiener Linien", url: "https://www.wienerlinien.at" },
  Prague: { label: "DPP", url: "https://www.dpp.cz" },
  Athens: { label: "STASY", url: "https://www.stasy.gr" },
  Istanbul: { label: "Metro İstanbul", url: "https://www.metro.istanbul" },
  Bangkok: { label: "BTS Skytrain", url: "https://www.bts.co.th" },
  Dubai: { label: "RTA Dubai", url: "https://www.rta.ae" },
  Doha: { label: "Qatar Rail", url: "https://www.qr.com.qa" },
  "Cape Town": { label: "MyCiTi", url: "https://www.myciti.org.za" },
  Sydney: { label: "Transport for NSW", url: "https://transportnsw.info" },
  "Los Angeles": { label: "LA Metro", url: "https://www.metro.net" },
  "San Francisco": { label: "BART", url: "https://www.bart.gov" },
  Chicago: { label: "CTA", url: "https://www.transitchicago.com" },
  Miami: { label: "Miami-Dade Transit", url: "https://www.miamidade.gov/global/transportation/transit.page" },
  "Mexico City": { label: "Metro CDMX", url: "https://www.metro.cdmx.gob.mx" },
  "Rio de Janeiro": { label: "MetrôRio", url: "https://www.metrorio.com.br" },
  "Buenos Aires": { label: "Subte (SBASE)", url: "https://www.buenosaires.gob.ar/subte" },
  Toronto: { label: "TTC", url: "https://www.ttc.ca" },
  Montreal: { label: "STM", url: "https://www.stm.info" },
  Vancouver: { label: "TransLink", url: "https://www.translink.ca" },
  Shanghai: { label: "Shanghai Metro", url: "https://en.shmetro.com" },
  Beijing: { label: "Beijing Subway", url: "https://www.bjsubway.com" },
  Mumbai: { label: "Mumbai Metro", url: "https://www.mmrcl.com" },
  "Kuala Lumpur": { label: "Rapid KL", url: "https://www.rapidkl.com.my" },
  Budapest: { label: "BKK", url: "https://bkk.hu" },
  Stockholm: { label: "SL", url: "https://sl.se" },
  Dublin: { label: "Transport for Ireland", url: "https://www.transportforireland.ie" },
};
