const app=document.getElementById("app"),toast=document.getElementById("toast"),alfred=document.getElementById("alfred");
let DB=null, selectedCity=localStorage.getItem("atlasCity")||"Tokyo", tripTab="overview";

async function loadData(){DB=await fetch("data.json").then(r=>r.json());render()}
function go(r){location.hash=r}function page(){return location.hash.slice(1)||"entry"}
function notify(m){toast.textContent=m;toast.classList.add("on");clearTimeout(window.__t);window.__t=setTimeout(()=>toast.classList.remove("on"),1800)}
function mark(mode){return `<div class="brand"><span class="brandmark">${mode==="MONDO"?"M":"A"}</span>${mode}</div>`}
function nav(mode){return `<header class="nav"><div class="shell navin">${mark(mode)}<nav class="navlinks">${mode==="MONDO"?`<button data-go="mondo">Accueil</button><button data-go="trips">Voyages</button><button data-go="create">Créer</button><button data-go="community">Communauté</button><button data-go="triproom">Trip Room</button>`:`<button data-go="atlas">Accueil</button><button data-go="destinations">Destinations</button><button data-go="city">Guides</button><button data-go="hotels">Hôtels</button><button data-go="flights">Vols</button>`}</nav><div class="navright"><div class="switch"><button class="${mode==="MONDO"?"on":""}" data-go="mondo">Mondo</button><button class="${mode==="ATLAS"?"on":""}" data-go="atlas">Atlas</button></div><button class="avatar" data-go="profile">NA</button></div></div></header>`}
function footer(){return `<footer class="footer shell"><div class="footergrid"><div>${mark("MONDO")}<h3>Rencontrer.<br>Organiser. Partir.</h3></div><div><h4>Mondo</h4><a data-go="trips">Voyages</a><a data-go="create">Créer</a><a data-go="community">Communauté</a><a data-go="triproom">Trip Room</a></div><div><h4>Atlas</h4><a data-go="destinations">Destinations</a><a data-go="hotels">Hôtels</a><a data-go="flights">Vols</a><a data-go="city">Guides</a></div><div><h4>Compte</h4><a data-go="profile">Profil</a><a data-alfred>Alfred</a></div></div></footer>`}
function fab(){return `<button class="alfredfab" data-alfred>Alfred</button>`}

function entry(){return `<main class="entry"><button class="entry-side" data-go="mondo"><img src="assets/entry-mondo.jpg"><div class="entry-info"><small>Mondo</small><h2>Partir à plusieurs.</h2><p>Trouvez les bonnes personnes et construisez l’aventure ensemble.</p><span class="entry-link">Entrer dans Mondo →</span></div></button><button class="entry-side" data-go="atlas"><img src="assets/entry-atlas.jpg"><div class="entry-info"><small>Atlas</small><h2>Explorer mieux.</h2><p>Comprenez la destination, préparez le séjour et rendez-le réservable.</p><span class="entry-link">Entrer dans Atlas →</span></div></button></main>`}

function mondoHome(){return `<main>${nav("MONDO")}<section class="hero shell"><div class="hero-grid"><div class="reveal"><div class="eyebrow">Communauté & organisation</div><h1>Le voyage commence par les bonnes personnes.</h1><p>Créez une idée simple, trouvez votre groupe, prenez les décisions ensemble puis laissez Atlas rendre le voyage possible.</p><div class="actions"><button class="btn primary" data-go="create">Créer un voyage</button><button class="btn" data-go="trips">Explorer les voyages</button></div></div><div class="hero-photo reveal"><img src="assets/mondo-hero.jpg"><div class="hero-caption"><h3>Une route, des inconnus, puis une histoire.</h3><p>Mondo doit donner envie de faire partie du groupe.</p></div></div></div></section><section class="section shell reveal"><div class="section-head"><div><div class="eyebrow">Voyages ouverts</div><h2>Rejoignez une aventure déjà en mouvement.</h2></div><p>Chaque projet expose dates, budget, itinéraire et personnes présentes avant même d’envoyer une demande.</p></div>${tripCards()}</section><section class="section shell reveal"><div class="band"><div><div class="eyebrow" style="color:#b8d5c8">Le dossier du groupe</div><h2>Une seule pièce pour tout décider.</h2><p>Discussion, itinéraire, décisions, budget et réservations vivent dans la même Trip Room.</p><button class="btn" data-go="triproom">Voir la Trip Room</button></div><div class="steps"><div class="step"><b>1. Publier une idée</b><small>Destination, période, budget, style.</small></div><div class="step"><b>2. Choisir le groupe</b><small>Demandes, profil, discussion avant acceptation.</small></div><div class="step"><b>3. Décider</b><small>Votes et décisions transformés en données de voyage.</small></div><div class="step"><b>4. Passer dans Atlas</b><small>Aucune information n’est redemandée.</small></div></div></div></section>${footer()}${fab()}</main>`}

function tripCards(){const t=[["Japon en octobre","Tokyo → Kyoto → Osaka","10–24 oct.","1 850 €","Tokyo"],["Bali entre amis","Ubud → Canggu → Lombok","3–17 nov.","1 420 €","Bangkok"],["Roadtrip Maroc","Marrakech → Atlas → Ouarzazate","14–21 sept.","780 €","Marrakech"]];return `<div class="tripgrid">${t.map((x,i)=>`<article class="tripcard"><img src="${DB.cities[x[4]].hero}"><div class="tripbody"><h3>${x[0]}</h3><p class="muted">${x[1]} · ${x[2]}</p><div class="tripmeta"><div class="faces"><span class="face">SA</span><span class="face">AM</span><span class="face">CL</span></div><b>${x[3]}</b></div><div class="trip-actions"><button class="btn" data-go="triproom">Voir le projet</button><button class="btn primary" data-go="join">Demander à rejoindre</button></div></div></article>`).join("")}</div>`}

function createTrip(){return `<main>${nav("MONDO")}<section class="hero shell" style="padding-bottom:10px"><div class="eyebrow">Créer un voyage</div><h1 style="max-width:800px">Une idée suffit pour commencer.</h1><p>On commence volontairement par très peu d’informations. Tout le reste se construit avec le groupe.</p></section><section class="section shell" style="padding-top:10px"><div class="creategrid"><article class="formcard"><h2>Votre projet</h2><div class="formgrid"><label class="field"><small>Destination</small><input value="Japon"></label><label class="field"><small>Période</small><input value="Octobre"></label><label class="field"><small>Durée</small><input value="14 jours"></label><label class="field"><small>Budget</small><input value="2 000 € / personne"></label><label class="field full"><small>L’idée</small><textarea rows="4">Tokyo, Kyoto et Osaka. Culture, food, quelques soirées, rythme tranquille.</textarea></label></div><div class="actions"><button class="btn primary" data-notify="Projet créé en démonstration.">Publier le voyage</button><button class="btn" data-go="trips">Voir les projets</button></div></article><aside class="formcard" style="background:var(--green2)"><div class="eyebrow">Après publication</div><h2>Mondo devient le dossier vivant du voyage.</h2><p class="muted">Demandes, messages, décisions, itinéraire et budget restent attachés au même objet Trip.</p></aside></div></section>${footer()}${fab()}</main>`}

function joinTrip(){return `<main>${nav("MONDO")}<section class="hero shell" style="padding-bottom:10px"><div class="eyebrow">Demander à rejoindre</div><h1>Japon en octobre.</h1><p>Présentez-vous à l’organisateur. La messagerie privée s’ouvre après validation.</p></section><section class="section shell" style="padding-top:10px"><div class="creategrid"><article class="formcard"><h2>Votre message</h2><textarea class="field" style="width:100%;min-height:150px;border:0" >Salut ! Je cherche justement un voyage au Japon en octobre. J’aime la food et la culture, le rythme me convient et le budget aussi.</textarea><button class="btn primary" data-notify="Demande envoyée à l’organisateur.">Envoyer la demande</button></article><aside class="formcard" style="background:var(--green2)"><div class="eyebrow">Règle Mondo</div><h2>Discuter avant de décider.</h2><p class="muted">L’organisateur peut accepter, refuser ou ouvrir une courte discussion avant de décider.</p></aside></div></section>${footer()}${fab()}</main>`}

function tripRoom(){const t=DB.trip;return `<main>${nav("MONDO")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Trip Room · JP-1048</div><h1>${t.title}</h1><p>${t.dates} · ${t.budget} · ${t.members.length} voyageurs</p></section><section class="section shell" style="padding-top:0"><div class="triproom"><section class="panel"><div class="tabs">${["overview","decisions","chat","budget","bookings"].map(x=>`<button class="${tripTab===x?"on":""}" data-tab="${x}">${{overview:"Vue d’ensemble",decisions:"Décisions",chat:"Discussion",budget:"Budget",bookings:"Réservations"}[x]}</button>`).join("")}</div>${tripTabContent()}</section><aside class="panel"><div class="eyebrow">Alfred</div><h2>Le voyage est prêt à passer dans Atlas.</h2><p class="muted">Dates, membres, itinéraire et budget sont déjà connus.</p><button class="btn primary" data-city="Tokyo">Préparer Tokyo dans Atlas</button><div class="joinrequest"><b>Lina souhaite rejoindre</b><p>“J’adore culture + food, budget OK.”</p><div class="actions"><button class="btn soft" data-notify="Lina acceptée.">Accepter</button><button class="btn" data-notify="Discussion ouverte avec Lina.">Discuter</button></div></div></aside></div></section>${footer()}${fab()}</main>`}
function tripTabContent(){const t=DB.trip;if(tripTab==="overview")return `<h2>Itinéraire</h2><div class="timeline">${t.route.map(x=>`<div class="timeitem"><b>${x}</b><p class="muted">Décisions et réservations liées à cette étape.</p></div>`).join("")}</div>`;if(tripTab==="decisions")return `<h2>Decision Room</h2>${t.decisions.map(d=>`<div class="decision"><div class="decision-head"><b>${d.q}</b><span class="tag">${d.status}</span></div><p>${d.result}</p>${d.status==="Ouvert"?`<div class="vote"><button data-notify="Vote enregistré : Shibuya">Shibuya</button><button data-notify="Vote enregistré : Shinjuku">Shinjuku</button></div>`:""}</div>`).join("")}`;if(tripTab==="chat")return `<h2>Discussion</h2><div class="chat"><div class="bubble">Sarah : Shibuya pour les soirées ?</div><div class="bubble me">Je préfère Shinjuku pour les transports.</div><div class="bubble">Alfred : je peux comparer les deux selon votre programme.</div></div>`;if(tripTab==="budget")return `<h2>Budget partagé</h2><div class="facts"><div class="fact"><small>Vol</small><b>620 €</b></div><div class="fact"><small>Hôtels</small><b>840 €</b></div><div class="fact"><small>Transport</small><b>160 €</b></div><div class="fact"><small>Marge</small><b>380 €</b></div></div>`;return `<h2>Réservations</h2><p class="muted">Aucune réservation confirmée. Atlas peut maintenant chercher vols et logements.</p><button class="btn primary" data-go="atlas">Ouvrir Atlas</button>`}

function community(){return `<main>${nav("MONDO")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Communauté</div><h1>Des conversations qui deviennent des départs.</h1><p>Les posts restent centrés sur des projets réels de voyage.</p></section><section class="section shell" style="padding-top:10px">${tripCards()}</section>${footer()}${fab()}</main>`}

function atlasHome(){return `<main>${nav("ATLAS")}<section class="hero shell"><div class="hero-grid"><div class="reveal"><div class="eyebrow">Guide premium · réservation · assistance</div><h1>Préparez le voyage, pas quinze onglets.</h1><p>Atlas commence par comprendre la ville, puis relie quartiers, hôtels, vols, transport, eSIM, articles et arrivée sur place.</p><div class="actions"><button class="btn primary" data-go="destinations">Choisir une destination</button><button class="btn" data-city="Tokyo">Voir Tokyo</button></div><div class="bookingbar"><div class="bookcell"><small>Destination</small><b>Tokyo</b></div><div class="bookcell"><small>Aller</small><b>10 oct.</b></div><div class="bookcell"><small>Retour</small><b>24 oct.</b></div><div class="bookcell"><small>Voyageurs</small><b>4</b></div><button class="btn primary" data-go="flights">Vols & hôtels</button></div></div><div class="hero-photo reveal"><img src="${DB.cities.Tokyo.hero}"><div class="hero-caption"><h3>Votre Tokyo commence par le bon quartier.</h3><p>Comprendre avant de réserver.</p></div></div></div></section><section class="section shell reveal"><div class="section-head"><div><div class="eyebrow">Votre Travel OS</div><h2>Les cinq choses qu’Atlas doit régler.</h2></div><p>Tout reste dans la destination, sans ouvrir de nouveaux onglets.</p></div><div class="prepare"><div><span>🗺️</span><b>Quartiers</b><small>où dormir selon votre style</small></div><div><span>🏨</span><b>Hôtels</b><small>sélection courte par budget</small></div><div><span>✈️</span><b>Vols</b><small>prix, fatigue, horaires</small></div><div><span>🚇</span><b>Transports</b><small>aéroport, métro, pass</small></div><div><span>📶</span><b>eSIM</b><small>connecté dès l’arrivée</small></div></div></section><section class="section shell reveal"><div class="section-head"><div><div class="eyebrow">Guides villes</div><h2>Commencez par comprendre l’endroit.</h2></div><p>Chaque ville est conçue comme un dossier complet de préparation.</p></div>${destGrid(Object.keys(DB.cities).slice(0,8))}</section>${footer()}${fab()}</main>`}
function destGrid(names){return `<div class="destgrid">${names.map(n=>{const c=DB.cities[n];return `<button class="dest" data-city="${n}"><img src="${c.hero}"><div class="destcopy"><h3>${n}</h3><p>${c.neighborhoods.slice(0,3).map(x=>x[0]).join(" · ")}</p></div></button>`}).join("")}</div>`}
function destinations(){return `<main>${nav("ATLAS")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Destinations</div><h1>Les villes qu’Atlas connaît vraiment.</h1><p>Peu de destinations au départ, mais chacune doit être exceptionnellement utile.</p></section><section class="section shell" style="padding-top:10px">${destGrid(Object.keys(DB.cities))}</section>${footer()}${fab()}</main>`}

function cityPage(){const c=DB.cities[selectedCity];return `<main>${nav("ATLAS")}<section class="cityhero shell"><div class="cityphoto"><img src="${c.hero}"><div class="citytitle"><div class="eyebrow" style="color:#fff">${c.country}</div><h1>${selectedCity}</h1><p>${c.intro}</p></div></div><div class="citynav"><button data-scroll="understand">Comprendre</button><button data-scroll="hoods">Quartiers</button><button data-scroll="stays">Hôtels</button><button data-scroll="transport">Transport</button><button data-scroll="esim">eSIM</button><button data-scroll="guides">Guides</button><button data-scroll="before">Before You Go</button><button data-scroll="first24">First 24h</button></div><div class="facts"><div class="fact"><small>Devise</small><b>${c.currency}</b></div><div class="fact"><small>Meilleure période</small><b>${c.best}</b></div><div class="fact"><small>Aéroport</small><b>${c.airport}</b></div><div class="fact"><small>Réseau</small><b>${c.transport}</b></div></div></section>
 <section class="section shell" id="understand"><div class="cityintro"><article class="storybox"><div class="eyebrow">Avant de réserver</div><h2>Quel ${selectedCity} voulez-vous vivre ?</h2><p>${c.intro}</p><div class="actions"><button class="btn primary" data-scroll="hoods">Comparer les quartiers</button><button class="btn" data-scroll="stays">Voir les hôtels</button></div></article><aside class="snapshot"><h3>Les quartiers en un coup d’œil</h3>${selectedCity==="Tokyo"?`<img src="assets/tokyo-map.jpg">`:`${simpleMap(c)}`}<p class="muted" style="font-size:9px">Vue explicative Atlas : elle sert à comprendre la ville, pas à remplacer une carte GPS.</p></aside></div></section>
 <section class="section shell" id="hoods"><div class="section-head"><div><div class="eyebrow">Quartiers</div><h2>Choisissez l’ambiance avant l’adresse.</h2></div><p>Atlas explique chaque zone avec des mots simples et une photo qui raconte l’atmosphère.</p></div><div class="hoodgrid">${c.neighborhoods.map(h=>hoodCard(h)).join("")}</div></section>
 <section class="section shell" id="stays"><div class="section-head"><div><div class="eyebrow">Atlas Stays</div><h2>Une sélection courte, par budget.</h2></div><p>3 Budget · 3 Confort · 3 Premium. Le reste reste accessible, mais Atlas fait d’abord le tri.</p></div>${hotelCards()}</section>
 <section class="section shell" id="transport"><div class="section-head"><div><div class="eyebrow">Se déplacer</div><h2>Aéroport, métro, pass : compris avant d’arriver.</h2></div><p>Le plan Atlas résume le réseau et donne les options d’arrivée selon le quartier.</p></div><div class="transgrid"><article class="transport"><h2>${c.transport}</h2><div class="metro">${metroSvg(c)}</div><p>Schéma simplifié, conçu pour comprendre le réseau en quelques secondes.</p></article><article class="transport"><h2>${c.airport} → ville</h2>${c.airportRoutes.map(r=>`<div class="route"><h3>${r[0]} · ${r[1]}</h3><p>${r[2]}</p><span class="source">Source éditoriale à vérifier</span></div>`).join("")}</article></div></section>
 <section class="section shell" id="esim"><div class="section-head"><div><div class="eyebrow">Atlas eSIM</div><h2>Internet dès l’atterrissage.</h2></div><p>${c.esim}. Comparez selon durée et volume, pas selon le forfait le plus cher.</p></div>${esimPlans()}</section>
 <section class="section shell" id="guides"><div class="section-head"><div><div class="eyebrow">Tout ce qu’on ouvre normalement ailleurs</div><h2>Les guides qui répondent aux vraies questions.</h2></div><p>Chaque article doit pouvoir déclencher une action : choisir un quartier, filtrer un vol, ajouter une journée ou réserver.</p></div><div class="articlegrid">${c.articles.map((a,i)=>articleCard(a,i)).join("")}</div></section>
 <section class="section shell" id="before"><div class="section-head"><div><div class="eyebrow">Atlas Before You Go</div><h2>Le voyage change à mesure que le départ approche.</h2></div></div><div class="countdown"><div class="count"><b>J−30</b><small>Activités à réserver</small></div><div class="count"><b>J−14</b><small>Formalités et documents</small></div><div class="count"><b>J−7</b><small>Météo, bagages, eSIM</small></div><div class="count"><b>J−2</b><small>Check-in, transfert, horaires</small></div></div></section>
 <section class="section shell" id="first24"><div class="section-head"><div><div class="eyebrow">Atlas First 24h</div><h2>Le jour où vous n’avez envie de réfléchir à rien.</h2></div></div><div class="cityintro"><article class="first24"><h2>Bienvenue à ${selectedCity}.</h2><div class="firststeps">${["Activer l’eSIM","Passer l’immigration","Rejoindre votre quartier","Check-in","Premier repas","Première balade légère"].map((x,i)=>`<div class="firststep"><span>${i+1}</span><div><b>${x}</b><p class="muted">Atlas affiche ici l’instruction utile au bon moment.</p></div></div>`).join("")}</div></article><aside class="before"><div class="eyebrow">Alfred Rescue</div><h2>Un problème ?</h2><p>Vol annulé, hôtel mauvais, train raté ou document perdu : Alfred réutilise tout le contexte du voyage avant de proposer une solution.</p><button class="btn primary" data-alfred>J’ai un problème</button></aside></div></section>${footer()}${fab()}</main>`}

function hoodCard(h){return `<article class="hood"><img src="${h[3]}"><div class="hoodbody"><h3>${h[0]}</h3><span class="tag">${h[1]}</span><p>${h[2]}</p><div class="hoodtags">${h[1].split(" · ").map(x=>`<span class="tag">${x}</span>`).join("")}</div></div></article>`}
function hotelCards(){const hs=DB.hotels[selectedCity],imgs=["https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=88","https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=88","https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=88"];return `<div class="hotelgrid">${hs.map((h,i)=>`<article class="stay"><div class="stayimg"><img src="${imgs[i%3]}"><span class="verified" style="position:absolute;left:10px;top:10px">${h.tier}</span></div><div class="staybody"><h3>${h.name}</h3><p>${h.desc}</p><div class="staymeta"><span><span class="source">ATLAS CANDIDATE</span><br><small>${h.neighborhood} · ${h.score}/10</small></span><span class="stayprice">${h.price} €</span></div><div class="stayactions"><button class="btn" data-notify="Fiche Atlas : literie, douche, bruit, breakfast, défauts.">Voir la fiche</button><button class="btn primary" data-notify="Réservation affiliée à connecter.">Réserver</button></div></div></article>`).join("")}</div><div class="actions"><button class="btn primary" data-go="hotels">Voir tous les logements</button><button class="btn" data-go="flights">Chercher le vol</button></div>`}
function simpleMap(c){const w=520,h=300,pts=c.neighborhoods.map((n,i)=>({x:75+(i%3)*170+(i%2)*20,y:70+Math.floor(i/3)*95,name:n[0],i}));return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;background:#eef2ef;border-radius:17px"><path d="M40 210 C100 80 250 35 420 80 C500 120 490 235 380 265 C250 300 100 285 40 210Z" fill="#dce7df"/>${pts.map(p=>`<g><circle cx="${p.x}" cy="${p.y}" r="22" fill="${["#6e72d9","#df9b47","#4ba36d","#b168a7","#5a9db7"][p.i%5]}" stroke="#fff" stroke-width="4"/><rect x="${p.x+18}" y="${p.y-14}" width="112" height="28" rx="9" fill="#fff"/><text x="${p.x+27}" y="${p.y+4}" font-size="11" font-family="DM Sans" fill="#27332d">${p.name}</text></g>`).join("")}</svg>`}
function metroSvg(c){const colors=["#e25a57","#3b8edb","#4ba36d","#d19a3f"],lines=c.transport.split(" · ").slice(0,4);return `<svg viewBox="0 0 620 300">${lines.map((l,i)=>{const y=60+i*65;return `<path d="M45 ${y} C160 ${y-30} 270 ${y+28} 390 ${y} S520 ${y-25} 575 ${y}" fill="none" stroke="${colors[i]}" stroke-width="8" stroke-linecap="round"/>${[80,200,320,440,555].map((x,k)=>`<circle cx="${x}" cy="${y+(k%2?4:-3)}" r="7" fill="#fff" stroke="${colors[i]}" stroke-width="4"/>`).join("")}<text x="45" y="${y-14}" font-size="11" font-family="DM Sans" fill="#4b5a52">${l}</text>`}).join("")}<rect x="245" y="108" width="135" height="70" rx="15" fill="#fff" stroke="#dbe3de"/><text x="267" y="139" font-size="12" font-family="DM Sans" font-weight="600" fill="#243129">Hub central</text><text x="267" y="157" font-size="9" font-family="DM Sans" fill="#6d7a73">correspondances</text></svg>`}
function esimPlans(){const plans=[["Essentiel","3–5 Go","7–15 jours","≈ 8–15 €"],["Voyage","10–20 Go","15–30 jours","≈ 18–35 €"],["Intensif","Gros volume","15–30 jours","≈ 30–60 €"]];return `<div class="esimplans">${plans.map((p,i)=>`<article class="esimplan ${i===1?"featured":""}">${i===1?'<span class="verified">Recommandé</span>':''}<h3>${p[0]}</h3><div class="stayprice">${p[3]}</div><div class="esimspec"><span>Données</span><b>${p[1]}</b></div><div class="esimspec"><span>Durée</span><b>${p[2]}</b></div><button class="btn ${i===1?"primary":""}" style="width:100%;margin-top:10px" data-notify="Comparateur eSIM affilié à connecter.">Voir les forfaits</button></article>`).join("")}</div>`}
function articleCard(a,i){const actions=["Comparer les quartiers","Filtrer les vols","Ajouter à mon voyage","Voir les hôtels","Ajouter au jour 2","Comparer le budget"];return `<article class="article ${i<2?"actionarticle":""}"><div><div class="eyebrow">${selectedCity}</div><h3>${a}</h3><p>Guide Atlas pensé pour répondre à une décision concrète du voyage, pas pour remplir un blog.</p></div>${i<6?`<div class="smartaction"><b>Pour votre voyage</b>${actions[i]} →</div>`:""}<button class="btn" data-notify="Article éditorial à produire dans le CMS Atlas.">Lire le guide</button></article>`}

function hotelsPage(){return `<main>${nav("ATLAS")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Atlas Stays · ${selectedCity}</div><h1>Choisissez peu. Choisissez bien.</h1><p>Budget, Confort, Premium et bientôt le véritable Choix Atlas.</p></section><section class="section shell" style="padding-top:10px">${hotelCards()}</section>${footer()}${fab()}</main>`}
function flightsPage(){return `<main>${nav("ATLAS")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Atlas Flights</div><h1>Le vol doit servir le voyage.</h1><p>Prix, bagages, horaires, escales et première journée sont comparés ensemble.</p></section><section class="section shell" style="padding-top:10px"><div class="flightsearch"><h2>Paris → ${selectedCity}</h2><div class="flightform"><div class="flightfield"><small>Départ</small><b>Paris CDG</b></div><div class="flightfield"><small>Destination</small><b>${selectedCity}</b></div><div class="flightfield"><small>Aller</small><b>10 oct.</b></div><div class="flightfield"><small>Retour</small><b>24 oct.</b></div><button class="btn primary" data-notify="API vols à connecter.">Rechercher</button></div><div class="flightoptions">${flightCard("Prix minimum","1 escale · arrivée tardive","548 €","Vous économisez 64 €, mais perdez probablement votre première soirée.")}${flightCard("Choix Atlas","1 escale courte · bons horaires","612 €","Meilleur compromis pour votre itinéraire.")}${flightCard("Direct","Temps et fatigue minimisés","742 €","+130 € pour économiser du temps et réduire la fatigue.")}</div></div></section>${footer()}${fab()}</main>`}
function flightCard(t,s,p,d){return `<article class="flightcard"><span class="tag">${t}</span><h3>${s}</h3><div class="flightprice">${p}</div><p>${d}</p><button class="btn primary" data-notify="Lien de réservation partenaire à connecter.">Voir l’offre</button></article>`}

function profile(){return `<main>${nav("MONDO")}<section class="hero shell" style="padding-bottom:20px"><div class="eyebrow">Profil voyageur</div><h1>Nassim</h1><p>Les centres d’intérêt et préférences vivent ici, pas sur les homepages.</p></section><section class="section shell" style="padding-top:10px"><div class="profilegrid"><article class="profilecard"><h2>Centres d’intérêt</h2>${["Aventure","Nature","Culture","Nightlife","Gastronomie","Détente"].map((x,i)=>`<div class="interest"><b>${x}</b><span>${[90,85,75,65,80,70][i]}/100</span></div>`).join("")}</article><article class="profilecard"><h2>Préférences Atlas</h2>${["Prix","Silence","Douche","Petit-déjeuner"].map((x,i)=>`<div class="interest"><b>${x}</b><span>${[88,82,78,74][i]}/100</span></div>`).join("")}</article></div></section>${footer()}${fab()}</main>`}

function showAlfred(){alfred.innerHTML=`<button class="btn" style="float:right" data-close>×</button><div class="eyebrow" style="color:#bad4c8">Alfred</div><h2>Je maintiens le voyage cohérent.</h2><div class="alfredcard">Votre groupe part au Japon du 10 au 24 octobre. Tokyo est la première étape. Budget : 2 000 € / personne.</div><div class="alfredcard"><b>Point à surveiller</b><br>Si vous choisissez Shibuya, 5 activités sauvegardées restent à moins de 25 minutes. Shinjuku gagne en transport interville.</div><button class="btn" data-city="Tokyo">Ouvrir Tokyo</button>`;alfred.classList.add("open");alfred.querySelector("[data-close]").onclick=()=>alfred.classList.remove("open");alfred.querySelector("[data-city]").onclick=()=>{selectedCity="Tokyo";localStorage.setItem("atlasCity","Tokyo");alfred.classList.remove("open");go("city")}}

function bind(){document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));document.querySelectorAll("[data-city]").forEach(x=>x.onclick=()=>{selectedCity=x.dataset.city;localStorage.setItem("atlasCity",selectedCity);go("city")});document.querySelectorAll("[data-notify]").forEach(x=>x.onclick=()=>notify(x.dataset.notify));document.querySelectorAll("[data-alfred]").forEach(x=>x.onclick=showAlfred);document.querySelectorAll("[data-scroll]").forEach(x=>x.onclick=()=>document.getElementById(x.dataset.scroll)?.scrollIntoView({behavior:"smooth",block:"start"}));document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{tripTab=x.dataset.tab;render()});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("on");io.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll(".reveal").forEach(x=>io.observe(x))}
function render(){if(!DB)return;alfred.classList.remove("open");const pages={entry,mondo:mondoHome,trips:mondoHome,create:createTrip,join:joinTrip,triproom:tripRoom,community,atlas:atlasHome,destinations,city:cityPage,hotels:hotelsPage,flights:flightsPage,profile};app.innerHTML=(pages[page()]||entry)();bind();scrollTo(0,0)}
window.addEventListener("hashchange",render);loadData();
